import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// import Navbar from "@/components/Navbar";
import { Toaster } from 'react-hot-toast';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <Navbar /> */}
         <Toaster
        position="top-right"
        toastOptions={{
          duration: 3000,
          style: {
            background: '#1f2937', // gray-800
            color: '#f9fafb',       // gray-50
            border: '1px solid #3b82f6', // blue-500
            borderRadius: '12px',
            padding: '14px 16px',
            fontSize: '14px',
            boxShadow: '0 4px 12px rgba(0,0,0,0.2)',
          },
          success: {
            iconTheme: {
              primary: '#10b981', // green-500
              secondary: '#ecfdf5', // green-50
            },
          },
          error: {
            iconTheme: {
              primary: '#ef4444', // red-500
              secondary: '#fef2f2', // red-50
            },
          },
        }}
      />
        {children}
      </body>
    </html>
  );
}
